package com.magneticstorm.app.ui.theme

import androidx.compose.ui.graphics.Color

// Світла тема — чистий, сучасний космічний стиль
val LightPrimary = Color(0xFF1565C0)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFD1E4FF)
val LightOnPrimaryContainer = Color(0xFF001D35)
val LightSecondary = Color(0xFF535F70)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFD7E3F7)
val LightOnSecondaryContainer = Color(0xFF101C2B)
val LightTertiary = Color(0xFF6B5778)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFFF2DAFF)
val LightOnTertiaryContainer = Color(0xFF251431)
val LightBackground = Color(0xFFF8FAFC)
val LightOnBackground = Color(0xFF191C1E)
val LightSurface = Color(0xFFF8FAFC)
val LightOnSurface = Color(0xFF191C1E)
val LightSurfaceVariant = Color(0xFFE0E2EC)
val LightOnSurfaceVariant = Color(0xFF43474E)
val LightOutline = Color(0xFF73777F)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)

// Темна тема — глибокий синій/фіолетовий, як нічне небо
val DarkPrimary = Color(0xFF9EC6FF)
val DarkOnPrimary = Color(0xFF003258)
val DarkPrimaryContainer = Color(0xFF00497D)
val DarkOnPrimaryContainer = Color(0xFFD1E4FF)
val DarkSecondary = Color(0xFFBBC7DB)
val DarkOnSecondary = Color(0xFF253140)
val DarkSecondaryContainer = Color(0xFF3B4858)
val DarkOnSecondaryContainer = Color(0xFFD7E3F7)
val DarkTertiary = Color(0xFFD6BEE4)
val DarkOnTertiary = Color(0xFF3B2948)
val DarkTertiaryContainer = Color(0xFF523F5F)
val DarkOnTertiaryContainer = Color(0xFFF2DAFF)
val DarkBackground = Color(0xFF0F1216)
val DarkOnBackground = Color(0xFFE1E3E6)
val DarkSurface = Color(0xFF0F1216)
val DarkOnSurface = Color(0xFFE1E3E6)
val DarkSurfaceVariant = Color(0xFF43474E)
val DarkOnSurfaceVariant = Color(0xFFC3C6CF)
val DarkOutline = Color(0xFF8D9199)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)

// Додаткові кольори для рівнів бурі (Kp)
val KpQuiet = Color(0xFF2E7D32)
val KpMinor = Color(0xFFF9A825)
val KpModerate = Color(0xFFEF6C00)
val KpStrong = Color(0xFFC62828)
val KpSevere = Color(0xFF7B1FA2)
val KpExtreme = Color(0xFF212121)
